definitions:
  service:
    name: サービス
    items: &serviceOptions
      appA:
        label: アプリケーションA
      appB:
        label: アプリケーションB
      appC:
        label: アプリケーションC
      all:
        label: 全サービス
  triage:
    name: 温度感
    items: &triageOptions
      emergency:
        label: ":fire: サービスに影響が出ており、緊急の対応が必要"
      investigate:
        label: ":mag: サービスに影響が出ている可能性があり、調査が必要"
      maintenance:
        label: ":wrench: 現時点でサービスに影響はないが、予防措置を取る"
  severity:
    name: インシデントレベル
    items: &severityOptions
      critical:
        label: ":police-car-light: Critical"
      major:
        label: ":prohibited: Major"
      minor:
        label: ":warning: Minor"
integration:
  slack:
    enabled: true
    baseChannelId: &baseChannelId C0606T6A3B5
    channelPrefix: inc_
flow:
  trigger:
    type: slack/command
    invoke: openInitialForm
  functions:
    - name: openInitialForm
      action: slack/openModal
      title: インシデントの疑いを報告
      elements:
        - type: header
          text: インシデントの疑いを報告
        - type: text
          text: インシデントの疑いを報告します。
        - type: checkbox
          elementId: selectService
          label: サービス
          options: *serviceOptions
        - type: radio
          elementId: selectTriage
          label: 温度感
          options: *triageOptions
        - type: textInput
          elementId: incidentDescription
          label: 発生している事象
          placeholder: 決済システムが500エラー
          multiline: true
        - type: note
          text: 今わかっていることをざっくりで構いません
      submit:
        label: 報告
      cancel:
        label: キャンセル
      invoke:
        - initialReport
        - createWarRoomChannel
        - invitePeoples
        - setPingCycle
    - name: initialReport
      action: slack/post
      channelId: *baseChannelId
      elements:
        - type: header
          text: インシデントの疑い
        - type: dl
          items:
            サービス: ${{input.selectService}}
            温度感: ${{input.selectTriage}}
            事象: ${{input.incidentDescription}}
            報告者: ${{trigger.user.name}}
        - type: channelSelect
          elementId: incidentChannel
          label: インシデントチャンネル
        - type: radio
          elementId: selectSeverity
          label: インシデントレベル
          options: *severityOptions
        - type: note
          text: インシデントのレベルを選択してください
        - type: select
          elementId: selectAssignee
          label: 担当者
          options:
            userA:
              label: ユーザーA
            userB:
              label: ユーザーB
            userC:
              label: ユーザーC
        - type: button
          elementId: reportButton
          label: 報告
          invoke: reportIncident
