integrations:
  slack:
    baseChannelId: &baseChannelId C0606T6A3B5
    channelPrefix: inc_
  datastore:
    type: dynamodb
    region: ap-northeast-1
    tableName: incident
definitions:
  service:
    name: サービス
    items: &serviceOptions
      delivery:
        label: 配送管理
      merchandise:
        label: 商品管理
      claim:
        label: 請求管理
      all:
        label: 全サービス
  triage:
    name: 温度感
    items: &triageOptions
      emergency:
        label: ":fire: サービスに影響が出ており、緊急の対応が必要"
      investigate:
        label: ":mag: サービスに影響が出ている可能性があり、調査が必要"
      maintenance:
        label: ":wrench: 現時点でサービスに影響はないが、予防措置を取る"
  severity:
    name: インシデントレベル
    items: &severityOptions
      critical:
        label: ":police-car-light: Critical"
      major:
        label: ":prohibited: Major"
      minor:
        label: ":warning: Minor"
flow:
  trigger:
    type: slack/command
    invoke: openInitialForm
  functions:
    - name: openInitialForm
      action: slack/openModal
      title: インシデントの疑いを報告
      elements:
        - type: header
          text: インシデントの疑いを報告
        - type: text
          text: インシデントの疑いを報告します。
        - type: checkbox
          elementId: selectService
          label: サービス
          options: *serviceOptions
        - type: radio
          elementId: selectTriage
          label: 温度感
          options: *triageOptions
        - type: textInput
          elementId: incidentDescription
          label: 発生している事象
          placeholder: 決済システムが500エラー
          multiline: true
        - type: note
          text: 今わかっていることをざっくりで構いません
      submit:
        label: 報告
      cancel:
        label: キャンセル
      invoke:
        - initialReport
        - createIncident
        # - createWarRoomChannel
        # - invitePeoples
        # - setPingCycle
    - name: initialReport
      action: slack/post
      channelId: *baseChannelId
      elements:
        - type: header
          text: ":rotating_light: ${{input.values.incidentDescription.value}} (${{input.values.selectTriage.label}})"
        - type: text
          text: <!here> インシデントの疑いが報告されました。
        - type: text
          text: ":fire: ${{input.values.selectTriage.label}}"
        # - type: divider
        - type: note
          text: 以下の情報を確認してください。
        - type: dl
          items:
            "サービス": ${{input.values.selectService.label}}
            "事象": ${{input.values.incidentDescription.value}}
            "報告者": <@${{input.user.id}}>
    - name: createIncident
      action: incident/create
      summary: ${{input.values.incidentDescription.value}}
      reporter:
        id: ${{input.user.id}}
        name: ${{input.user.name}}
      metadata:
        service:
          - label: ${{input.values.selectService.label}}
            value: ${{input.values.selectService.value}}
        triage:
          label: ${{input.values.selectTriage.label}}
          value: ${{input.values.selectTriage.value}}
notificationGroups:
  executive: &executive
    label: 事業部長
    ids:
      - U06042X1P29 # demo EC事業部長
  teamDelivery: &teamDelivery
    label: 配送管理チーム
    ids:
      - U05V6EBAGG7 # demo 配送T dev
      - U05V6EBD087 # demo 配送T dev
      - U060W0FU9ME # demo 配送T mgr
  teamMerchandise: &teamMerchandise
    label: 商品管理チーム
    ids:
      - U06070MSEF4 # demo 商品T dev
      - U06042WPP9B # demo 商品T dev
      - U0609DVTLKW # demo 商品T mgr
  teamClaim: &teamClaim
    label: 請求管理チーム
    ids:
      - U060KKCKK17 # demo 請求T dev
      - U05V6EBJ3AB # demo 請求T dev
      - U0606T6F61H # demo 請求T mgr
  sre: &sre
    label: SRE
    ids:
      - U0606T6PQG3 # demo SRE
  pdm: &pdm
    label: PdM
    ids:
      - U06070MR5DG # demo PdM
notificationPolicies:
  - label: "(温度感 = emergency || severity = critical) && service = 配送サービス => 配送管理チーム, 事業部長, SRE, PdM"
    condition:
      op: and
      conditions:
        - op: or
          conditions:
            - op: anyOf
              property: triage
              values:
                - emergency
            - op: anyOf
              property: severity
              values:
                - critical
        - op: anyOf
          property: service
          values:
            - delivery
    recipients:
      - *executive
      - *teamDelivery
      - *sre
      - *pdm
fallbackNotificationPolicy:
  - *teamDelivery
  - *teamMerchandise
  - *teamClaim
  - *sre
