integration:
  slack:
    baseChannelId: &baseChannelId C0606T6A3B5
    channelPrefix: inc_
  datastore:
    type: dynamodb
    region: ap-northeast-1
    tableName: incident
stdField:
  description:
    name: 概要
    placeholder: 決済システムが500エラー
  services:
    name: 影響サービス
    items:
      - code: delivery
        value: "配送管理"
      - code: merchandise
        value: "商品管理"
      - code: claim
        value: "請求管理"
      - code: all
        value: "全サービス"
  level:
    name: インシデントレベル
    items:
      - code: sev1
        value: ":police-car-light: SEV1"
      - code: sev2
        value: ":prohibited: SEV2"
      - code: sev3
        value: ":warning: SEV3"
      - code: sev4
        value: ":man-facepalming: SEV4"
      - code: sev5
        value: ":eyes: SEV5"
customField:
  triage:
    type: enum
    name: 温度感
    multiple: false
    items:
      - code: open
        value: 未対応
      - code: inProgress
        value: 対応中
      - code: resolved
        value: 解決済
flow:
  trigger:
    type: slack/command
    invoke: openInitialForm
  function:
    - name: openInitialForm
      action: slack/openModal
      title: インシデントの疑いを報告
      elements:
        - type: header
          text: インシデントの疑いを報告
        - type: text
          text: インシデントの疑いを報告します。
        - type: fillField
          field: std.services
          label: 影響サービス
        - type: fillField
          field: custom.triage
          label: 温度感
        - type: fillField
          field: std.description
          label: 発生している事象
        - type: note
          text: 今わかっていることをざっくりで構いません
      submit:
        label: 報告
      cancel:
        label: キャンセル
      invoke:
        - initialReport
        - createIncident
        # - createWarRoomChannel
        # - invitePeoples
        # - setPingCycle
    - name: initialReport
      action: slack/post
      channelId: *baseChannelId
      elements:
        - type: header
          text: ":rotating_light: ${{std.description.value}} (${{custom.triage.value}})"
        - type: text
          text: <!here> インシデントの疑いが報告されました。
        - type: text
          text: ":fire: ${{custom.triage.value}}"
        - type: divider
        - type: note
          text: 以下の情報を確認してください。
        - type: dl
          items:
            "サービス": ${{std.services.value}}
            "事象": ${{std.description.value}}
            "報告者": <@${{input.user.id}}>
    - name: createIncident
      action: datastore/createIncident
notificationGroups:
  executive: &executive
    label: 事業部長
    ids:
      - U06042X1P29 # demo EC事業部長
  teamDelivery: &teamDelivery
    label: 配送管理チーム
    ids:
      - U05V6EBAGG7 # demo 配送T dev
      - U05V6EBD087 # demo 配送T dev
      - U060W0FU9ME # demo 配送T mgr
  teamMerchandise: &teamMerchandise
    label: 商品管理チーム
    ids:
      - U06070MSEF4 # demo 商品T dev
      - U06042WPP9B # demo 商品T dev
      - U0609DVTLKW # demo 商品T mgr
  teamClaim: &teamClaim
    label: 請求管理チーム
    ids:
      - U060KKCKK17 # demo 請求T dev
      - U05V6EBJ3AB # demo 請求T dev
      - U0606T6F61H # demo 請求T mgr
  sre: &sre
    label: SRE
    ids:
      - U0606T6PQG3 # demo SRE
  pdm: &pdm
    label: PdM
    ids:
      - U06070MR5DG # demo PdM
notificationPolicies:
  - label: "(温度感 = emergency || severity = critical) && service = 配送サービス => 配送管理チーム, 事業部長, SRE, PdM"
    condition:
      op: and
      conditions:
        - op: or
          conditions:
            - op: anyOf
              property: triage
              values:
                - emergency
            - op: anyOf
              property: severity
              values:
                - critical
        - op: anyOf
          property: service
          values:
            - delivery
    recipients:
      - *executive
      - *teamDelivery
      - *sre
      - *pdm
fallbackNotificationPolicy:
  - *teamDelivery
  - *teamMerchandise
  - *teamClaim
  - *sre
